CREATE TYPE "public"."email_types" AS ENUM('NOTIFY_APPLICANT_WITHDRAW', 'NOTIFY_APPLICANT_CLOSE', 'NOTIFY_APPLICANT_REVOKE', 'NOTIFY_APPLICANT_DAC_REVIEW_REJECTED', 'NOTIFY_APPLICANT_DAC_APPROVAL', 'NOTIFY_COLLABORATORS_DAC_APPROVAL', 'REMINDER_SUBMIT_DRAFT', 'REMINDER_SUBMIT_INSTITUTIONAL_REP_REVIEW', 'REMINDER_SUBMIT_REVISIONS_INSTITUTIONAL_REP', 'REMINDER_SUBMIT_DAC_REVIEW', 'REMINDER_SUBMIT_REVISIONS_DAC_REVIEW', 'REMINDER_REQUEST_REVISIONS_INSTITUTIONAL_REP', 'REMINDER_REQUEST_REVISIONS_DAC_REVIEW', 'REQUEST_REVISIONS_INSTITUTIONAL_REP', 'REQUEST_REVISIONS_DAC_REVIEW', 'SUBMIT_DRAFT', 'SUBMIT_REVISIONS_INSTITUTIONAL_REP', 'SUBMIT_INSTITUTIONAL_REP_REVIEW', 'SUBMIT_REVISIONS_DAC_REVIEW', 'SUBMIT_DAC_REVIEW');--> statement-breakpoint
CREATE TABLE "emails" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "emails_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"application_action_id" bigint NOT NULL,
	"created_at" timestamp NOT NULL,
	"email_type" "email_types" NOT NULL,
	"recipient_emails" varchar(320) NOT NULL
);
