/*
 * Copyright (c) 2024 The Ontario Institute for Cancer Research. All rights reserved
 *
 * This program and the accompanying materials are made available under the terms of
 * the GNU Affero General Public License v3.0. You should have received a copy of the
 * GNU Affero General Public License along with this program.
 *  If not, see <http://www.gnu.org/licenses/>.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 * IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

import { z } from 'zod';

const MOLECULAR_LABS = [
	'CHILDRENS_HOSPITAL_OF_EASTERN_ONTARIO_OTTAWA',
	'HAMILTON_HEALTH_SCIENCES_HAMILTON',
	'HOSPITAL_FOR_SICK_CHILDREN_TORONTO',
	'KINGSTON_HEALTH_SCIENCES_CENTRE_KINGSTON',
	'LONDON_HEALTH_SCIENCES_CENTRE_LONDON',
	'NORTH_YORK_GENERAL_HOSPITAL_TORONTO',
	'SINAI_HEALTH_SYSTEM_TORONTO',
	'TRILLIUM_HEALTH_PARTNERS_MISSISSAUGA',
	'UNIVERSITY_HEALTH_NETWORK_TORONTO',
] as const;

export const MolecularLab = z.enum(MOLECULAR_LABS);
export type MolecularLab = z.infer<typeof MolecularLab>;
