/*
 * Copyright (c) 2024 The Ontario Institute for Cancer Research. All rights reserved
 *
 * This program and the accompanying materials are made available under the terms of
 * the GNU Affero General Public License v3.0. You should have received a copy of the
 * GNU Affero General Public License along with this program.
 *  If not, see <http://www.gnu.org/licenses/>.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 * IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

import { z } from 'zod';

// TODO: the enums for the following have been shortened due to a 63-byte limit to names (NAMEDATALEN) in Postgres
// - BONES_JOINTS_AND_ARTICULAR_CARTILAGE_OF_OTHER_AND_UNSPECIFIED_SITES => BONES_JOINTS_AND_ARTICULAR_CARTILAGE_AND_OTHER_SITES
// - OTHER_AND_ILL_DEFINED_SITES_WITHIN_RESPIRATORY_SYSTEM_AND_INTRATHORACIC_ORGANS => OTHER_ILL_DEFINED_SITES_RESPIRATORY_SYSTEM_INTRATHORACIC_ORGANS
// - SPINAL_CORD_CRANIAL_NERVES_AND_OTHER_PARTS_OF_CENTRAL_NERVOUS_SYSTEM => SPINAL_CORD_CRANIAL_NERVES_PARTS_OF_CENTRAL_NERVOUS_SYSTEM
// For consistency the enums will be the same in Prisma + Zod, but the UI dictionary will need to use the full string definition
// Refer to the primary site terminologies list in the Data Model for the expected definitions
// Ticket ref: https://github.com/OHCRN/platform/issues/513
export const PRIMARY_CANCER_DIAGNOSIS = [
	'UNKNOWN_PRIMARY_SITE',
	'ACCESSORY_SINUSES',
	'ADRENAL_GLAND',
	'ANUS_AND_ANAL_CANAL',
	'BASE_OF_TONGUE',
	'BLADDER',
	'BONES_JOINTS_AND_ARTICULAR_CARTILAGE_OF_LIMBS',
	'BONES_JOINTS_AND_ARTICULAR_CARTILAGE_AND_OTHER_SITES',
	'BRAIN',
	'BREAST',
	'BRONCHUS_AND_LUNG',
	'CERVIX_UTERI',
	'COLON',
	'CONNECTIVE_SUBCUTANEOUS_AND_OTHER_SOFT_TISSUES',
	'CORPUS_UTERI',
	'ESOPHAGUS',
	'EYE_AND_ADNEXA',
	'FLOOR_OF_MOUTH',
	'GALLBLADDER',
	'GUM',
	'HEART_MEDIASTINUM_AND_PLEURA',
	'HEMATOPOIETIC_AND_RETICULOENDOTHELIAL_SYSTEMS',
	'HYPOPHARYNX',
	'KIDNEY',
	'LARYNX',
	'LIP',
	'LIVER_AND_INTRAHEPATIC_BILE_DUCTS',
	'LYMPH_NODES',
	'MENINGES',
	'NASAL_CAVITY_AND_MIDDLE_EAR',
	'NASOPHARYNX',
	'OROPHARYNX',
	'OTHER_AND_ILL_DEFINED_DIGESTIVE_ORGANS',
	'OTHER_AND_ILL_DEFINED_SITES',
	'OTHER_AND_ILL_DEFINED_SITES_IN_LIP_ORAL_CAVITY_AND_PHARYNX',
	'OTHER_ILL_DEFINED_SITES_RESPIRATORY_SYSTEM_INTRATHORACIC_ORGANS',
	'OTHER_AND_UNSPECIFIED_FEMALE_GENITAL_ORGANS',
	'OTHER_AND_UNSPECIFIED_MAJOR_SALIVARY_GLANDS',
	'OTHER_AND_UNSPECIFIED_MALE_GENITAL_ORGANS',
	'OTHER_AND_UNSPECIFIED_PARTS_OF_BILIARY_TRACT',
	'OTHER_AND_UNSPECIFIED_PARTS_OF_MOUTH',
	'OTHER_AND_UNSPECIFIED_PARTS_OF_TONGUE',
	'OTHER_AND_UNSPECIFIED_URINARY_ORGANS',
	'OTHER_ENDOCRINE_GLANDS_AND_RELATED_STRUCTURES',
	'OVARY',
	'PALATE',
	'PANCREAS',
	'PAROTID_GLAND',
	'PENIS',
	'PERIPHERAL_NERVES_AND_AUTONOMIC_NERVOUS_SYSTEM',
	'PLACENTA',
	'PROSTATE_GLAND',
	'PYRIFORM_SINUS',
	'RECTOSIGMOID_JUNCTION',
	'RECTUM',
	'RENAL_PELVIS',
	'RETROPERITONEUM_AND_PERITONEUM',
	'SKIN',
	'SMALL_INTESTINE',
	'SPINAL_CORD_CRANIAL_NERVES_PARTS_OF_CENTRAL_NERVOUS_SYSTEM',
	'STOMACH',
	'TESTIS',
	'THYMUS',
	'THYROID_GLAND',
	'TONSIL',
	'TRACHEA',
	'URETER',
	'UTERUS_NOS',
	'VAGINA',
	'VULVA',
] as const;

export const PrimaryCancerDiagnosis = z.enum(PRIMARY_CANCER_DIAGNOSIS);
export type PrimaryCancerDiagnosis = z.infer<typeof PrimaryCancerDiagnosis>;
