name: pcgl-daco-database

services:
  postgres:
    image: postgres:15-alpine
    container_name: pcgl-daco-postgres
    ports:
      - 5432:5432
    volumes:
      - daco-api-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mypassword

volumes:
  daco-api-db:
    name: daco-api-db
    driver: local
